AllCops:
  Exclude:
    - 'bin/**/*'
    - 'files/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - Gemfile
  DefaultFormatter: progress
  DisplayStyleGuide: true
  StyleGuideBaseURL: https://github.com/bbatsov/ruby-style-guide
  ExtraDetails: true

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
